# Generated by Django 5.2.8 on 2025-11-20 06:23

import audio_process.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CallRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        upload_to=audio_process.models.upload_path,
                        verbose_name="녹음 파일",
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("processed", models.BooleanField(default=False)),
                ("duration", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "call_recordings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpeakerSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speaker_label", models.CharField(max_length=50)),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField()),
                ("text", models.TextField()),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="audio_process.callrecording",
                    ),
                ),
            ],
            options={
                "db_table": "speaker_segments",
                "ordering": ["start_time"],
            },
        ),
    ]
