# Generated by Django 5.2.8 on 2025-11-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio_process", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakersegment",
            name="is_counselor",
            field=models.BooleanField(default=False),
        ),
    ]
