# Generated by Django 5.2.8 on 2025-11-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio_process", "0002_speakersegment_is_counselor"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakersegment",
            name="emotion_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="speakersegment",
            name="emotion_label",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
