# Generated by Django 5.2.8 on 2025-11-19 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audio_process", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                ("label_type", models.CharField(max_length=20)),
                ("confidence", models.FloatField()),
                ("probabilities", models.JSONField(blank=True, default=dict)),
                (
                    "action",
                    models.CharField(
                        default="MONITOR", max_length=50, verbose_name="필터링 조치"
                    ),
                ),
                (
                    "alert_level",
                    models.CharField(
                        default="LOW", max_length=50, verbose_name="경고 레벨"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "segment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logical_analysis",
                        to="audio_process.callsegment",
                        verbose_name="분석 대상 구간",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 논리 분석 결과",
                "ordering": ["-created_at"],
            },
        ),
    ]
