# Generated by Django 5.1.2 on 2025-11-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio_process', '0003_speakersegment_emotion_confidence_and_more'),
        ('logical_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, verbose_name='세션 ID')),
                ('text', models.TextField(verbose_name='분석 텍스트')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='분류 라벨')),
                ('label_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='라벨 타입')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='신뢰도')),
                ('probabilities', models.JSONField(blank=True, null=True, verbose_name='확률 분포')),
                ('action', models.CharField(blank=True, max_length=100, null=True, verbose_name='권장 조치')),
                ('alert_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='경고 수준')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='분석 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('segment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logical_result', to='audio_process.speakersegment', verbose_name='연결된 세그먼트')),
            ],
            options={
                'verbose_name': '논리 분석 결과',
                'verbose_name_plural': '논리 분석 결과 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ClassificationResult',
        ),
    ]
