# Generated by Django 5.2.8 on 2025-11-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logical_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classificationresult",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="classificationresult",
            name="action",
            field=models.CharField(
                choices=[
                    ("TERMINATE_CALL", "통화 중단"),
                    ("WARN", "경고"),
                    ("SUPPORT_AGENT", "상담사 지원"),
                    ("MONITOR", "모니터링"),
                ],
                default="MONITOR",
                max_length=50,
                verbose_name="필터링 조치",
            ),
        ),
        migrations.AddField(
            model_name="classificationresult",
            name="alert_level",
            field=models.CharField(
                choices=[
                    ("CRITICAL", "매우 심각"),
                    ("HIGH", "심각"),
                    ("MEDIUM", "보통"),
                    ("LOW", "낮음"),
                ],
                default="LOW",
                max_length=50,
                verbose_name="경고 레벨",
            ),
        ),
    ]
