# Generated by Django 5.2.8 on 2025-11-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logical_analysis", "0002_alter_classificationresult_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classificationresult",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="classificationresult",
            name="action",
            field=models.CharField(
                default="MONITOR", max_length=50, verbose_name="필터링 조치"
            ),
        ),
        migrations.AlterField(
            model_name="classificationresult",
            name="alert_level",
            field=models.CharField(
                default="LOW", max_length=50, verbose_name="경고 레벨"
            ),
        ),
    ]
