# Generated by Django 5.2.8 on 2025-11-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="생성일"
            ),
        ),
    ]
