# Generated by Django 5.2.8 on 2025-11-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_department_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_image",
        ),
    ]
