# Generated by Django 5.2.8 on 2025-11-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emotion_analysis", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="callsegment",
            name="recording",
        ),
        migrations.DeleteModel(
            name="CallRecording",
        ),
        migrations.DeleteModel(
            name="CallSegment",
        ),
    ]
