# Generated by Django 5.2.8 on 2025-11-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "emotion_analysis",
            "0002_remove_callsegment_recording_delete_callrecording_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EmotionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("text", "Text"), ("audio", "Audio")], max_length=20
                    ),
                ),
                ("input_text", models.TextField()),
                ("emotion_label", models.CharField(max_length=50)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
